Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

-  Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지.
-  많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함.
-  Numpy의 기본 데이터 타입은 ndarray.ndarray를 이용하여 넘파이에서 다차열 배열을 쉽게 생성하고 다양한 연산을 수행함.

Numpy 특징

 - 강력한 N차원 배열 객체
 - 정교한 브로드케스팅 기능
 - 유용한 선형 대수학, 푸리에 변환 및 난수 기능
 - 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
 - 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
 !pip install numpy (Numpy설치)

ERROR: Invalid requirement: '(Numpy설치)'


In [2]:
import numpy as np
z = np.arange(10)    #1차원 배열
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%time for _  in range(10): my_array2 = my_arr * 2     #시간재기 일반

Wall time: 36.3 ms


In [5]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]  #시간재기 배열방식

Wall time: 1.52 s


In [6]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분포에서 난수 매트릭스 array생성
data = np.random.randn(2,3) #표준 정규분포로 구성되는 2행 3열 매트릭스 만들기(무작위로)
print(data, '\n')      # 표준 정규분표 요소로 만듦
print(data * 10 , '\n')  # 요소에다가 10을 곱한 값
print(data + data)     #data와 data를 더한 값

[[-0.08865147  1.17899351 -0.13956361]
 [ 0.40610069 -0.20150913  0.71264515]] 

[[-0.88651475 11.78993507 -1.39563608]
 [ 4.06100689 -2.01509125  7.1264515 ]] 

[[-0.17730295  2.35798701 -0.27912722]
 [ 0.81220138 -0.40301825  1.4252903 ]]


In [7]:
# 위의 행렬에 대한 정보제공 범례
print(data.shape)  # 데이타 크기
print(data.dtype) # 데이타 타입
print(data.ndim) # 차원을 알려줌

(2, 3)
float64
2


 다차원 배열
 <img src = 'numpy차원.jpg' STYLE= 'width:300px;'>

In [8]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [9]:
print(arr2.ndim,'\n')   #행렬의 차원
print(arr2.shape)       #행렬의 크기


2 

(2, 4)


In [10]:
#1차원 배열로 3개의 데이터 
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape)   #(,열)이 아닌 (열,) 형태로 출력한다

[1 2 3] <class 'numpy.ndarray'> (3,)


In [11]:
#2차원 배열로 2개의 row(행)와 3개의 column(열)으로 구성된 6개의 데이터
array2 = np.array([[1,2,3],[2,3,4]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)


In [12]:
#1개의 row(행)과 3개의 column으로 구성된 2차원 배열(유의!!) -> 대괄호 하나를 더 첨가하여 2차원으로 표시
array21 = np.array([[1,2,3]])
print(array21,array21.shape)

[[1 2 3]] (1, 3)


In [13]:
#3차원
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]]],dtype=object)   #dtype은 객체
print(array3,array3.shape,'\n')
print(type(array3))                   #(차원의 수{2행5열이 몇개},행,렬)

[[[1 2 3 4 5]
  [6 7 8 9 10]]

 [[1 2 3 4 5]
  [6 7 8 9 10]]

 [[1 2 3 4 5]
  [6 7 8 9 10]]] (3, 2, 5) 

<class 'numpy.ndarray'>


In [14]:
#경고 메시지 제외 처리
import warnings                             
warnings.filterwarnings('ignore')

배열 생성 및 초기화
 -  Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full,eye함수제공
 - 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [15]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')     #3행6열배열 - 안의 값은 0
print(np.zeros((2,3,2)))   #3행 2열의 3차원 요소값은 0

#이미지 데이터의 빈그릇을 만들때 사용

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [16]:
print(np.ones((2,3,2)))   #전부 요소값은 1 (1뒤에 .은 실수를 표현함), .을 없애려면 ,dtype =int를 작성하면됨

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [17]:
ar1 =np.full((2,2),5)  #2행 2열을 전부 5로 출력(전부 특정한 수로 출력-)
ar1

array([[5, 5],
       [5, 5]])

In [18]:
#항등행렬(대각선), 단위행렬
ar2 = np.eye(3)    
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# [과제] zeros_like, ones_like, full_like 함수를 사용하여 예를 하나씩 작성하세요.(구글링가능)

In [20]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()

ar1 = np.zeros_like(a)
ar2 = ar1.astype(float)
print(ar2, ar2.dtype)
print()

ar3 = np.ones_like(a)
ar4 = ar3.astype(float)
print(ar4, ar4.dtype)
print()

ar5 = np.full_like(a, 6)
ar6 = ar5.astype('float32')
print(ar6, ar6.dtype)
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]] float32



In [21]:
v1= np.array([1,2,3])
z1 = np.zeros_like(v1)

In [22]:
#arange 함수 : python의 range함수의 배열 버전(걸리는 시간이 짧다)
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr2 = range(15)    # 사용하려면 for문을 사용해야되는데 걸리는 시간이 더 길다
arr2            

range(0, 15)

In [24]:
arr2 = arr1.reshape(3,5)    #reshape = 형태를 다시 만듦
print(arr2,arr2.shape,'\n')
arr3 = arr1.reshape(1,3,5)
print(arr3,arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [25]:
# Q.  array1을 생성하고 에 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요
array1 = np.arange(10)
array2 = array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
# 0~29 일차원 배열을 생성한 후 다시 2,3차원 배열로 변환하여 출력하세요.
arr1 = np.arange(30)
arr2 = arr1.reshape(5,6)
print(arr2,arr2.shape,'\n')
arr3 = arr2.reshape(2,3,5)
print(array3,array3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[1 2 3 4 5]
  [6 7 8 9 10]]

 [[1 2 3 4 5]
  [6 7 8 9 10]]

 [[1 2 3 4 5]
  [6 7 8 9 10]]] (3, 2, 5)


In [27]:
# reshape(-1,-1)이용, 차원 변경   -1을 사용하여 알아서 계산하게 만듦
array1 = np.arange(30)
ar12 = array1.reshape(5,-1)   #행은 5개 나머지는 알아서 계산할것, 계산 가능한 것으로 해야함
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [28]:
# 2차원을 1차원 or 3차원으로 변환
ar1 = ar12.reshape(-1,)    #가능한 콤마를 같이 할것
ar3 = ar12.reshape(-1,2,5)
print(ar1,ar1.shape,'\n')
print(ar3,ar3.shape,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [29]:
#3차원을 1,2차원으로 변환하여 출력하세요
ar4 = ar3.reshape(-1,)
ar5 = ar3.reshape(3,-1)
print(ar4,ar4.reshape,'\n')
print(ar5,ar5.reshape,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] <built-in method reshape of numpy.ndarray object at 0x0000015EA9010D50> 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] <built-in method reshape of numpy.ndarray object at 0x0000015EA8CC3450> 



In [30]:
ar3 = np.arange(30).reshape(3,2,5)
ar31 = ar3.reshape(-1,)
ar32 = ar3.reshape(3,-1)

print(ar31,'\n')
print(ar32)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


행렬의 종류
 -  정방행렬은 행과 열의 수가 같은 행렬
 -  대각행렬은 주 대각선 원소를 제외한 모든 원소들이 0인 정방행렬
 -  항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
 -  영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
 -  전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
 -  직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬 

In [31]:
# 정방행렬

ar = np.full((5,5),7)
ar 

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [32]:
# 항등행렬, 단위행렬
a = np.eye(5)
a 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#ndarray 데이터 형태 지정 및 변경

<img src = '데이터형태.jpg' STYLE= 'width:300px;'>

In [34]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)

[1. 2. 3.] float64
[1 2 3] int32


In [35]:
#타입 변경
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
#empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다.
#cf. zeros함수와 비교(zeros함수는 초기화하나 empty함수는 메모리 안에 있음-초기화 안함)
# empty 함수를 실행할 때 마다 값이 다른것을 확인 할 수있다. 이는 해당 메모리 영역에 어떤 데이터가 
#남아 있었던지 상관없이 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.

print(np.empty(shape=(10,),dtype=np.int8))
print(np.zeros(shape=(10,),dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]


In [39]:
#문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4],dtype='S')
arr = np.array([1,2,3,4],dtype=np.string_)   #>>따옴표 없이 사용함
print(arr, arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [40]:
arr1 = arr.astype(float)  #타입을 float로 변경하면 실수가 됨> 자동인식
# 만약 float 32를 써야 한다면 'float32'로 변경하면됨
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float64


In [41]:
arr1 = arr.astype(int)  #타입을 int로 변경하면 정수가 됨
print(arr1,arr1.dtype)

[1 2 3 4] int32


In [42]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용하여 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
array_e1 = np.array(list_e)     #배열로 바꿈
print(array_e1,array_e1.dtype,'\n')
array_e2 = array_e1.astype(int)  #e1을 정수로 바꿈
print(array_e2,array_e2.dtype)

[1.2 2.3 3. ] float64 

[1 2 3] int32


In [43]:
# 배열의 산술 연산
arr = np.array([[1,2,3],[4,5,6]])   #2차원 배열
arr = np.arange(1,7).reshape(2,3)   #
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [44]:
#곱셈(같은 위치로)
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [45]:
#뺄셈
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:

arr2 = np.array([[0.,4,1],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [47]:
# 부등호
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [48]:
# 기본 사칙연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)

print(value1)
print(value2,'\n')
print(value1 + value2)
print(np.add(value1,value2),'\n')
print(value1 * value2)
print(np.multiply(value2,value1),'\n')
print(value2 - value1)
print(np.subtract(value2,value1),'\n')
print(value2/value1)
print(np.divide(value2,value1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]] 

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [49]:
arr = np.random.randn(2,2)
arr

array([[0.74184024, 0.17071103],
       [0.12813729, 1.15354472]])

In [50]:
arr.mean().round(4)   #mean->평균, round(수소점 n까지 나타냄)

0.5486

In [51]:
arr.mean(axis=1)  #열방향으로 평균(가로)

array([0.45627564, 0.64084101])

In [52]:
arr.mean(axis=0)  #행방향의 평균(세로)

array([0.43498876, 0.66212788])

In [53]:
arr.sum().round(4)

2.1942

In [54]:
arr.cumprod()  #누적으로 곱한 값

array([0.74184024, 0.12664031, 0.01622735, 0.01871897])

In [55]:
# 인덱싱,슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[2]  #2번째 열

array([7, 8, 9])

In [57]:
arr2d[2][2] #2번째 열과 2번째 행 (0->1->2), (0->1->2)

9

In [58]:
arr2d[:,0]  #앞에는 행 전부, 뒤에는 0번째 열

array([1, 4, 7])

In [59]:
arr2d[:2,:] #:2(슬라이싱)-> 0부터 1까지 슬라이싱하여 1,2열, :를 사용하여 행 전부

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
# arr2d에서 [3,6],[[1,2],[4,5]]를 출력하세요
arr2d[:2,2],arr2d[:2,:2]

(array([3, 6]),
 array([[1, 2],
        [4, 5]]))

In [61]:
#arr2d를 다음과 같은 방식으로 아래와 같이 출력하세요
#[[1,2,3]
#[4,5,6]]


In [62]:
arr2d[[0,1],:]  #리스트의 형식으로 할수 있음.

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr =np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [64]:
[14,15,16]
[3,9]
[1,7,13]

[1, 7, 13]

In [65]:
arr[2,[2,3,4]]
arr[2][2:5]    #2번째 행 , 2부터 5앞까지의 열(2~4열)

array([14, 15, 16])

In [66]:
arr[[0,1],3]   #리스트 형태로
arr[:2,3]      #슬라이싱형태

array([3, 9])

In [67]:
arr[[0,1,2],1]
arr[:3,1]

array([ 1,  7, 13])

In [68]:
#배열을 리스트로 변환
li = arr.tolist()
print(li,type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [69]:
# Boolean indexing  불특정,특정조건에 맞는것은 true 아닌것은 false(참인것만 판별함) - 자주 사용함-
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]   #[]를 이용하여 조건을 걸어줌
print(arr3)              #true만 뽑힘
print(arr1d > 5)         #true,false판별

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [70]:
# arr1d에서 일반 인덱스를 이용해서 [6,7,8,9]를 출력하세요
arr1d[5:]


array([6, 7, 8, 9])

In [71]:
# Q. 1~14까지 ndarry를 만들어 array_e로 저장하고 (array_e/2)>5를 만족하는 값을 불린 인덱싱으로 출력하세요.
 
array_e = np.arange(1,15)
arr1 = array_e[(array_e/2)>5]
print(arr1)
    


[11 12 13 14]


In [72]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[ 1.92027207  0.35849439  0.87986279 -0.30824811]
 [ 0.46891326  1.46596276 -1.49039517  0.98772245]
 [ 1.52641742 -1.23765739 -0.5820634  -0.08269221]
 [-0.97824891 -0.11237714  0.25107636  1.12043987]
 [ 0.41848184  0.05869697  1.10415895  0.77461071]
 [-1.21513591  0.38641459 -0.64853466  1.35679482]
 [-1.84681834 -0.09831791 -1.39912216 -0.74254342]]


In [73]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [74]:
data[names =='Bob']

array([[ 1.92027207,  0.35849439,  0.87986279, -0.30824811],
       [-0.97824891, -0.11237714,  0.25107636,  1.12043987]])

In [75]:
data[names =='Bob',2:]

array([[ 0.87986279, -0.30824811],
       [ 0.25107636,  1.12043987]])

In [76]:
data[names != 'Bob'] #(Bob이 아닌것)

array([[ 0.46891326,  1.46596276, -1.49039517,  0.98772245],
       [ 1.52641742, -1.23765739, -0.5820634 , -0.08269221],
       [ 0.41848184,  0.05869697,  1.10415895,  0.77461071],
       [-1.21513591,  0.38641459, -0.64853466,  1.35679482],
       [-1.84681834, -0.09831791, -1.39912216, -0.74254342]])

In [77]:
# Bob이거나 Will 인것을 출력
data[(names =='Bob') | (names =='Will')]

mask = (names =='Bob') | (names =='Will')
data[mask]

array([[ 1.92027207,  0.35849439,  0.87986279, -0.30824811],
       [ 1.52641742, -1.23765739, -0.5820634 , -0.08269221],
       [-0.97824891, -0.11237714,  0.25107636,  1.12043987],
       [ 0.41848184,  0.05869697,  1.10415895,  0.77461071]])

In [78]:
#음수를 모두 0으로 바꾸어서 출력
data[data<0] =0
print(data)

[[1.92027207 0.35849439 0.87986279 0.        ]
 [0.46891326 1.46596276 0.         0.98772245]
 [1.52641742 0.         0.         0.        ]
 [0.         0.         0.25107636 1.12043987]
 [0.41848184 0.05869697 1.10415895 0.77461071]
 [0.         0.38641459 0.         1.35679482]
 [0.         0.         0.         0.        ]]


In [79]:
#[과제] 1~100까지의 정수에서 3의 배수인 것만 출력(for문과 배열 두가지 방식)

import numpy as np
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [80]:
for num in range(1,101):
    if num%3 == 0:
       print(num,end= ' ')
    else:
        continue

3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 

In [81]:
arr=np.arange(1,101)
print(arr[arr%3==0])
print()

li = []
arr_li=arr.tolist()
for i in arr_li:
    if i%3==0:
        li.append(i)
print(i,end=" ")


[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]

100 

In [82]:
#[과제] 1~100까지의 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)

In [83]:
for num in range (1,101):
    if (num%2 == 0) & (num%5 == 0):
        print(num,end=' ')
    else:
        continue

10 20 30 40 50 60 70 80 90 100 

In [84]:

import numpy as np
arr = np.arange(10,101,10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [85]:
li = []
for i in range(1,101):
    if i % 5 == 0 and i % 2 == 0:
        li.append(i)
print(li)
        
arr = np.arange(1,101)
arr2 = arr[arr % 10 == 0]
print(arr2)


[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [86]:
#[과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요
arr = np.random.randn(5,5)
print(arr, '\n')
# 표준정규분포 평균
arr.mean()


[[ 1.15397509  0.07440921  0.0383494   1.12484146  0.3389977 ]
 [-0.9600154   2.1143004  -1.3133954  -1.56354448  1.08613243]
 [-1.11095549  1.25799033 -0.53075294  0.90066229 -0.01313055]
 [ 0.64028022  0.53269974 -2.30683056  0.16618548  0.54913269]
 [-1.40741547  0.17715226  0.80345899  0.33272161  0.87280781]] 



0.11832227264872472

In [87]:
arr1 = np.random.randn(10000,10000)
print(arr1.mean())
print(arr1.std())

4.9228604319102494e-05
1.0000138378540344


In [88]:
#표준 정규분포 표준편차
arr.std()

1.0371988685878113

In [89]:
#[과제] 현재 사용하고 있는 numpy의 버전을 출력하세요

In [90]:
import numpy
print(numpy.__version__)

1.20.3


In [91]:
#[과제] numpy 함수의 도움말 기능을 볼 수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요

In [92]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [94]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
#array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [95]:
n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [96]:
a = np.arange(10,dtype = float)
b = np.zeros_like(a)
b[4]=1
b


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [97]:
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

[과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array([0,1,2,3,4,5,6,7,8,9])

In [99]:
li=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
li[9::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [100]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_desc = np.sort(array)[::-1]
print(array_desc)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#[과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스의 방식으로 출력하세요

In [101]:
# arr1d = np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

In [102]:
import numpy as np

Array = np.array([1,2,0,0,4,0])
index = [2,3,5]
Array_e = np.delete(Array, index)
print(Array_e)

[1 2 4]


In [103]:
# 0이 아닌 인덱스 반환
a= np.array([1,2,0,0,4,0])
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

In [104]:
# Fancy indexing
arr = np.empty((8,4))    #형태만 8행4열 틀만 만들어줌(무작위 숫자)
arr
for i in range(8):       #0~7까지의 숫자를 8행 4열로 만들어줌
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [105]:
arr[[4,3,0,6]]     #자기가 원하는 행만 출력

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [106]:
arr[[-3,-5,-7]]    #역순의 방식으로 행을 출력( -1 , -2,-3~~)

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [107]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

arr[[1,5,7,2],[0,3,1,2]]    # 원하는 특정 숫자를 [[행],[열]] 의 방식으로 출력 ex 10 =>[[2],[2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [108]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]])   #앞의 행렬은 그대로 오고 0->3->1->2열의 순서대로 작성

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [109]:
# 배열 전치와 축 바꾸기
arr = np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)        #T:transform(전치) : 행을 열로 변형

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
