In [5]:
import numpy as np  #numpy를 하기위해서 항상 먼저 작성하고 실행 시켜야함
import pandas as pd

In [4]:
arr = np.random.randint(1,10, size =(5,5)) #randint(무작위로 정수를 추출)=>1~10사이에 있는 정수들을 5,5로 무작위로 출력
arr

array([[2, 1, 6, 3, 5],
       [8, 9, 8, 5, 4],
       [5, 1, 9, 9, 6],
       [4, 5, 4, 7, 2],
       [2, 6, 3, 4, 2]])

In [5]:
arr.T  #T : 행과열이 서로 바뀐다(전치)

array([[2, 8, 5, 4, 2],
       [1, 9, 1, 5, 6],
       [6, 8, 9, 4, 3],
       [3, 5, 9, 7, 4],
       [5, 4, 6, 2, 2]])

In [6]:
np.transpose(arr) #np.transpose형태로도 가능 


array([[2, 8, 5, 4, 2],
       [1, 9, 1, 5, 6],
       [6, 8, 9, 4, 3],
       [3, 5, 9, 7, 4],
       [5, 4, 6, 2, 2]])

In [7]:
#행렬곱과 내적(딥러닝에서 중요함)
np.dot(arr.T,arr)

array([[113, 111, 143, 127,  84],
       [111, 144, 125, 116,  69],
       [143, 125, 206, 179, 130],
       [127, 116, 179, 180, 111],
       [ 84,  69, 130, 111,  85]])

In [8]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

#2행3열 => 3행2열로 변환 ** 0은 2차원(열), 1은 1차원(행)
y = np.swapaxes(a,0,1)
print(y,'\n') 


[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 



In [9]:
y = np.transpose(a)
print(y)

[[0 3]
 [1 4]
 [2 5]]


In [10]:
y = a.T
print(y)

[[0 3]
 [1 4]
 [2 5]]


In [11]:
# Q. 1 ~ 100을 아래와 같이 출력하세요.
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


SyntaxError: invalid syntax (Temp/ipykernel_6012/1049642885.py, line 2)

In [12]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [13]:
arr = np.arange(1,101).reshape(10,10)
for i in range(1,10):
    if i % 2 == 1:
        arr[i] = arr[i][::-1]
print(arr, type(arr))


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [14]:
# (0,1,2) 0:3차원,1:2차원,3:1차원
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) => (2,1,3) *(3차원,2차원,1차원)
a =np.arange(6).reshape(1,2,3)  #3차원1개, 2차원2개 1차원 3개
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))   #3차원 2개, 2차원1개 1차원 2개
print(y,y.shape,'\n')


[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [15]:
# (1,2,3) => (2,3,1) 
a = np.arange(6).reshape(1,2,3)  #3차원1개 ,2행3열(2차원 2개 1차원 3개)
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0))  #3차원 2개, 3행1열    (0,1,2) => 1,2,0으로 변환
print(y,y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [16]:
#. [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 



In [52]:
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

y = np.transpose(arr,(1,0,2))  
print(y,y.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [ ]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요.

In [48]:
#나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])  #배열을 구할때는 np.array는 기본임
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [51]:
# 각 수의 역수를 구해주는 함수(tuple) => reciprocal
value = np.array([0,85,1.85,1,100])
print(np.reciprocal(value))

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1,dtype=float))

[       inf 0.01176471 0.54054054 1.         0.01      ]
[100] 

[0.01]


C:\Users\admin\Anaconda3\envs\cakd5\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in reciprocal
  This is separate from the ipykernel package so we can avoid doing imports until


In [54]:
# 승수의 결과값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))   # 2의 1승, 10의 2승, 15의 3승

[  4 100 225] 

[   2  100 3375]


In [66]:
arr = np.random.randn(10)
#print(arr.mean(),'\n')   #mean : 평균
#print(arr.std())    #std : 표준편차
arr

array([-0.99185765, -0.017324  , -1.73150598,  0.92066503, -1.09667587,
        0.75244251,  1.80395224,  0.31976084,  1.58836296, -1.665607  ])

In [67]:
#양수인 원소의 개수
(arr > 0).sum()   #조건을 만족하는 개수.sum

5

In [68]:
# 하나 이상의 값이 True인지 검사 (boolean)
bools = np.array([False,False,True,True])
bools.any()

True

In [69]:
# 모든 원소가 True인지 검사
bools.all()

False

In [71]:
# 삼항식의 벡터화 버전(조건을 만족하면)
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0 ,2 ,-2)   #arr>0 이면 2, 아닐경우( 0 이거나 음수) -2

[[-0.06532326  0.54853623  0.70194877  1.26544737]
 [ 0.21779619 -1.43319325  0.350015   -1.094192  ]
 [ 0.32257968  1.08353919 -1.57378352  0.12039715]
 [-0.01395492  0.62103891  1.15072478  0.89087021]] 



array([[-2,  2,  2,  2],
       [ 2, -2,  2, -2],
       [ 2,  2, -2,  2],
       [-2,  2,  2,  2]])

In [72]:
#arr의 모든 양수를 2로 바꿀 경우
np.where(arr > 0,2,arr)  # arr>0 일 경우에만 2, 나머지는 그대로arr을 작성

array([[-0.06532326,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.43319325,  2.        , -1.094192  ],
       [ 2.        ,  2.        , -1.57378352,  2.        ],
       [-0.01395492,  2.        ,  2.        ,  2.        ]])

In [80]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y)짝을 만들수 잇는 2차원 배열 2개 반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [88]:
# np.sort() 순서대로 숫자를 정렬하는 함수
np.random.seed(0)   # 랜덤 숫자를 고정시키는 함수
arr = np.random.randint(1,100, size=10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 

[45 48 65 68 68 10 84 22 37 88]


In [89]:
#np.sort는 원본은 반영되지 않는다. 출력은 가능
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [94]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행,열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d)
sort_ar2d_axis0 = np.sort(arr2d,axis=0 )  #axis =0 행
print(sort_ar2d_axis0,'\n')         # 위, 아래의 행을 서로 바꿈
sort_ar2d_axis1 = np.sort(arr2d,axis=1)  #axis =1 열
print(sort_ar2d_axis1)        #2행의 배열을 앞뒤로 변경

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [99]:
#ndarray.sort() : 원본 반영 => 배열에 바로 sort를 씀
np.random.seed(0)
arr = np.random.randint(1,10,size=10)
#arr = np.random.randn(6)
print(arr,'\n')
arr.sort()  # 원본 반영(배열.sort)
print(arr)

[6 1 4 4 8 4 6 3 5 8] 



array([1, 3, 4, 4, 4, 5, 6, 6, 8, 8])

In [105]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 열방향 정렬 default
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)  #1은 종방향
print(arr)


[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [107]:
#횡방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort()    #0은 횡방향 =>
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [108]:
# 정렬된 행렬의 인덱스 반환(argsort) : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices                       # 작은 숫자 순서대로 인덱스 번호가 앞으로 배정된다.

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [109]:
#배열에서 정렬한 후 5%에 해당되는 원소만 출력 (할때마다 바뀜 => 고정시키려면 random.seed()를 앞에 붙인다)
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

-1.6721886708490616

In [110]:
# 배열 집합 연산(문자,숫자) => 중복을 피함
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [1]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))   #종복제외

['Bob', 'Joe', 'Will']

In [2]:
#첫번재 배열의 원소가 두번째 배열의 원소를 포함하는 지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])    #첫번째 배열의 원소가, 두번째 배열(2,3,6)을 포함하는지 여부

array([ True, False, False,  True,  True, False,  True])

In [3]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식으로 입출력 .npy file로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [4]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#여러개를 한꺼번에 저장
#np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [9]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0 ] 을 출력하세요
a = np.ones(10,dtype=int)
a


[1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [28]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)


[1 0 1 0 1 0 1 0 1 0]


In [19]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력
a= np.arange(10)
a1 = a[a>5]
a1


array([6, 7, 8, 9])

In [21]:
# Q. a에서 최대값, 최소값 인덱스 출력
print(max(a),min(a))

9 0


In [22]:
a =np.arange(1,10)
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

최댓값: 8
최솟값: 0


In [ ]:
# Q a에서 인덱스 배열을 역순으로 출력하세요

In [24]:
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [ ]:
#Q. np.ones((10,10))을 아래와 같이 출력하세요
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [3]:
import numpy as np
b=np.ones((10,10))
b[1:9,1:9]=0
b


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#[도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요 


In [ ]:
#[과제] np.ones((5,5))을 아래와 같이 출력하세요
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [17]:
b=np.zeros((9,9))
b[2:7,2:7]=1
b


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
b = np.ones((5,5))
arr = b.arr

In [ ]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식 인덱싱,tile방식)
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


In [31]:
b = np.zeros((8,8), dtype=int)
b[[1,3,5,7],[0,2,4,6]]=1  
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0]])

In [34]:
a = np.array([[0,1,0,1],[1,0,1,0]])
np.tile(a,(4,2))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# [도전과제] np.arange(4)를 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


[파이썬 random 함수]

In [44]:
import random
print(random.random(),'\n') #0.0 <= x <1.0 사이
print(random.randint(1,10),'\n')  #1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20),'\n') # min max사이 float리턴
print(random.randrange(10),'\n') # 지정범위 int값을 지정
print(random.choice([1,2,3,4,5]),'\n') #리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li)   #리스트 요소를 다시 섞어서 린턴
print(li)


0.9742004201645091 

9 

18.47893204569474 

6 

3 

[3, 5, 2] 

[3, 5, 1, 2, 4]


[numpy random함수]

- np.random.seed  :  seed를 통한 난수 생성
- np.random.randint  :  정수 난수 1개 생성
- np.random.rand  :  0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn  :  가우시안 표준 정규분포에서 난수  매트릭스 배열 생성
- np.random.shuffle  :  기존의 데이터 순서 바꾸기
- np.random.choice  :  기존 데이터에서 sampling 

In [53]:
print(np.random.randint(6), '\n')  # 0~5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1~19까지 정수인 난수 1개
print(np.random.randint(10,size=10),'\n')  #0에서 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n')  # 10에서 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5)))  # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

3 

9 

[4 0 3 6 9 0 2 8 3 8] 

[17 14 10 19 15 18 17 12 13 15] 

[[10 18 12 17 11]
 [13 19 14 15 17]
 [15 17 17 12 16]]


In [49]:
r = np.random.rand(6)  # 0 ~ 1 사이의 균일분포
print(r,'\n')
r.mean()

[0.92367184 0.04466746 0.68390444 0.39979562 0.53051995 0.37566187] 



0.4930368648998121

In [31]:
# 표준 정규분포 
r = np.random.randn(6)
print(r,'\n')
r.mean()

[-0.70702942 -0.62686981  0.20349052 -0.9748533  -0.41723524  0.81450272] 



-0.28466575545955625

In [53]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([1, 4, 5, 2, 3])

In [54]:
np.random.choice(list)

4

In [55]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts=True)
print(index)   #unique한 숫자를 추출
print(count)  #2,3,7,11의 갯수

[ 2  3  7 11]
[3 2 1 2]


In [58]:
np.random.uniform(1.0,2.0, 10)

array([1.58646537, 1.68151094, 1.97550979, 1.08455562, 1.61193221,
       1.45481624, 1.79126734, 1.66154005, 1.27455196, 1.33765732])

In [3]:
print(np.random.uniform(0,1,(2,3)))   #최대, 최소값을 지정함 

[[0.43053967 0.75487148 0.72176729]
 [0.22168412 0.5338501  0.78587806]]


In [57]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음 
np.random.random_sample((2,3))

array([[0.67364491, 0.33432474, 0.44857534],
       [0.35376261, 0.29685328, 0.17526121]])

In [61]:
!pip install pandas

In [7]:
ar = np.random.rand(4,8)  #rand는 균일분포
ar

array([[0.09122515, 0.15722206, 0.39748393, 0.63877192, 0.457907  ,
        0.76484824, 0.78349832, 0.81919947],
       [0.69943432, 0.49327942, 0.47106977, 0.23876503, 0.70332819,
        0.19214196, 0.29888798, 0.77101969],
       [0.09047603, 0.21781636, 0.99489477, 0.82079653, 0.44444129,
        0.48236628, 0.26392249, 0.39455605],
       [0.62610247, 0.01003733, 0.64715409, 0.55254735, 0.73756492,
        0.70100572, 0.94329671, 0.99121302]])

In [8]:
# 배열을 데이타프레임으로 변환  (우선 ar의 rand로 만든다)  >>> (열이 있다)
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))

          0         1         2         3         4         5         6  \
0  0.091225  0.157222  0.397484  0.638772  0.457907  0.764848  0.783498   
1  0.699434  0.493279  0.471070  0.238765  0.703328  0.192142  0.298888   
2  0.090476  0.217816  0.994895  0.820797  0.444441  0.482366  0.263922   
3  0.626102  0.010037  0.647154  0.552547  0.737565  0.701006  0.943297   

          7  
0  0.819199  
1  0.771020  
2  0.394556  
3  0.991213   <class 'pandas.core.frame.DataFrame'>


In [11]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.091225  0.157222  0.397484  0.638772  0.457907  0.764848  0.783498   
1  0.699434  0.493279  0.471070  0.238765  0.703328  0.192142  0.298888   
2  0.090476  0.217816  0.994895  0.820797  0.444441  0.482366  0.263922   
3  0.626102  0.010037  0.647154  0.552547  0.737565  0.701006  0.943297   

       time  
0  0.819199  
1  0.771020  
2  0.394556  
3  0.991213

In [27]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df




ID Gender Age
1  2451      M  20
2  1314      M  20
3  4214      F  30

In [24]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df
h = np.zeros((3, 10))
id_ = np.random.randint(1, 1000, size = (1, 10))
gender = np.random.randint(2, size = (1, 10))
age = np.random.randint(0, 120, size = (1, 10))

h[0] = id_
h[1] = gender
h[2] = age

h = np.transpose(h)

columns = ['id', 'gender', 'age']
index = np.arange(1, 11)
df = pd.DataFrame(h, index, columns = columns)

df


id  gender    age
1   830.0     1.0    1.0
2   696.0     0.0   15.0
3   301.0     1.0  118.0
4   730.0     0.0   44.0
5   633.0     1.0  115.0
6   870.0     1.0   43.0
7    55.0     1.0   29.0
8   392.0     0.0   12.0
9   913.0     0.0   73.0
10  835.0     0.0   82.0

In [67]:
ar = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]   
df = pd.DataFrame(ar,index,columns=columns)
#df.id = np.array([1,2,3,4])
df.id= np.arange(1,5)     # 값이 많으면 random함수를 써서 작성
#df.gender = np.array([0,1,0,1])
np.random.seed(0)
df.gender = np.random.randint(2,size=4)
#df.age = np.array([20,30,40,50])
df.age = np.arange(1,5)*10
df



id  gender  age
0   1       0   10
1   2       1   20
2   3       1   30
3   4       0   40

#[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터 프레임으로 변환하여 출력하세요.(관측치 = 행, 1000개)
 - id: 1~1000번 일련번호
 - gender : 0,1정수 난수 생성
 - age : 0~80사이 정수 난수 생성
 - region : 1~10사이의 정수 난수 생성
 - product_19 : 제품코드 11111 ~ 99999
 - product_20 : 제품코드 11111 ~ 99999
 - price_19: 1000~50000 사이 실수 난수 생성
 - price_20: 1000~50000 사이 실수 난수 생성
 - quantity_19:1~100 사이 정수 난수 생성
 - quantity_20:1~100 사이 정수 난수 생성
 - time_19:01~24 사이 정수 난수 생성
 - time_20:01~24 사이 정수 난수 생성
 - amount_19:price_19* quantity_19
 - amount_20:price_20* quantity_20
 - sales : 19년 대비 20년 구매금액이 증가하면1, 감소하면 0
 

In [72]:
ar = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]   
df = pd.DataFrame(ar,index,columns=columns)
#df.id = np.array([1,2,3,4])
df.id= np.arange(1,5)     # 값이 많으면 random함수를 써서 작성
#df.gender = np.array([0,1,0,1])
np.random.seed(0)
df.gender = np.random.randint(2,size=4)
#df.age = np.array([20,30,40,50])
df.age = np.arange(1,5)*10
df

id  gender  age
0   1       0   10
1   2       1   20
2   3       1   30
3   4       0   40

In [9]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

customer = 10000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),\
                  columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(111,222,size = customer)
df.product_20 = np.random.randint(111,222,size = customer)

pricearray= np.random.randint(10,500,size = 1000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0
print(df.shape)
df

(10000, 14)


id gender  age  product_19  product_20  price_19  price_20  \
1          1      M   10         134         129     32700     20500   
2          2      F   36         182         186     13000     42200   
3          3      F   79         122         161     47600      1100   
4          4      M   33         197         154     44200     36600   
5          5      F   59         146         173     26900     22500   
...      ...    ...  ...         ...         ...       ...       ...   
9996    9996      M    3         218         179     40100     48800   
9997    9997      F   33         167         214     23900     18400   
9998    9998      M   34         130         184     17300     25700   
9999    9999      F   10         113         210     12800     45300   
10000  10000      M   72         185         116     19900     10700   

       quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1               51           65       21        3    1667700    1332500      0  
2               89           27       22       21    1157000    1139400      0  
3               70           24        4       19    3332000      26400      0  
4               34            7       18       21    1502800     256200      0  
5               89           28       12       11    2394100     630000      0  
...            ...          ...      ...      ...        ...        ...    ...  
9996            23            8        9       15     922300     390400      0  
9997             3           50       15       24      71700     920000      1  
9998            11           91       10       24     190300    2338700      1  
9999            62           57        7        4     793600    2582100      1  
10000           66           68       23        6    1313400     727600      0  

[10000 rows x 14 columns]

In [8]:
df[df.sales==0]
print(len(df[df.sales==0]))
# df[df.sales==1].head()

5034
