## 판다스

 - 판다스를 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
 - 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
 - 시리즈 인덱스는 데이터값과 일대일 대응, 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)
 - Contents
   - Series(변환, 인덱스 구조, 원소 선택)
   - DataFrame(변환, 인덱스, 삭제, 선택, 추가, 변경, 전치 등)
  

라이브러리 > 모듈 > 클래스 > 함수
import : 외장(파이썬 할때 같이 설치)

In [3]:
# 딕셔러니를 시리즈로 변환
import pandas as pd  #pd:판다스의 별칭

dic_data = {'a':1,'b':2,'c':3}
sr = pd.Series(dic_data)
print(sr,type(sr))

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


In [5]:
# 리스트를 시리즈로 변환

list_data = ['2021-01-29',3.14,'BBC',752,True]
sr = pd.Series(list_data, index=['a','b','c','d','e'])
print(sr,type(sr))

a    2021-01-29
b          3.14
c           BBC
d           752
e          True
dtype: object <class 'pandas.core.series.Series'>


In [8]:
idx = sr.index
print(idx)
val = sr.values
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2021-01-29' 3.14 'BBC' 752 True]


In [9]:
# 튜플을 시리즈로 변환
tup_data = ('영인','2015-05-04','여',True)
sr = pd.Series(tup_data,index=['이름','생년월일','성별','학생여부'])
print(sr,type(sr))

이름              영인
생년월일    2015-05-04
성별               여
학생여부          True
dtype: object <class 'pandas.core.series.Series'>


In [10]:
print(sr[0])    # 정수 위치 인덱스
print(sr['이름'],'\n')   #이름 인덱스
#둘다 결과는 같다.

영인
영인 



In [14]:
print(sr['생년월일':'성별'],'\n')
print(sr[1:3])

생년월일    2015-05-04
성별               여
dtype: object 

생년월일    2015-05-04
성별               여
dtype: object


In [15]:
print(sr[[1,3]])  # 대괄호 하나 더 있으면 각각 추출 가능

생년월일    2015-05-04
학생여부          True
dtype: object


In [16]:
#배열을 시리즈로 변환
import numpy as np

s1 = np.arange(start=11,stop=16)
s2 = pd.Series(s1,index=['ED1','ED2','ED3','ED4','ED5'])    #배열을 넣고 인덱스를 넣는다
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [19]:
print(s2[1:3],'\n')

ED2    12
ED3    13
dtype: int32 



In [17]:
print(s2[1:3],'\n')

ED2    12
ED3    13
dtype: int32


In [22]:
#Series를 배열로 변환

print(type(s2))
# 배열로 전환하는 공식
ar = np.array(s2)
print(ar,type(ar))

<class 'pandas.core.series.Series'>
[11 12 13 14 15] <class 'numpy.ndarray'>


In [ ]:
# Q. 4가지 자료형 데이터를 생성하고 각각 Series로 변환하여 출력하세요

In [25]:
dic_data = {'restroy':1,'Prots':2,'Champberry':3,'Annecy':4}
sr = pd.Series(dic_data)
print(sr,type(sr))

restroy       1
Prots         2
Champberry    3
Annecy        4
dtype: int64 <class 'pandas.core.series.Series'>


In [27]:
list_data = ['restory','Pros','Champberry','Annecy']
sr = pd.Series(list_data, index=['x','y','z','k'])
print(sr,type(sr))

x       restory
y          Pros
z    Champberry
k        Annecy
dtype: object <class 'pandas.core.series.Series'>


In [28]:
tup_data = ('restory','Pros','Champberry','Annecy')
sr = pd.Series(tup_data,index=['restory','Pros','Champberry','Annecy'])
print(sr,type(sr))

restory          restory
Pros                Pros
Champberry    Champberry
Annecy            Annecy
dtype: object <class 'pandas.core.series.Series'>


In [29]:
s1 = np.arange(start=11,stop=16)
s2 = pd.Series(s1,index=['ED1','ED2','ED3','ED4','ED5'])   
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [33]:
data = np.arange(1000,5000,1000)
obj = pd.Series(data)
state = ['Califonia','Ohio','Oregon','Texas']
obj.name = 'population'
obj.index = state
# obj.index.name = 'state' 데이터의 이름을 짓는방법
obj

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [34]:
obj. Califonia = np.nan   #nan = null(nan을 설정하는방법1)
obj

Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [39]:
obj['Newyork'] = 3000   #중간에 추가하고 싶을때 사용한다.
obj

Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Newyork      3000.0
Name: population, dtype: float64

In [37]:
obj['Califonia']  # nan을 설정하는 방법 2

nan

In [40]:
obj.Newyork   #데이터에서 뉴욕을 확인

3000

In [35]:
obj.isnull()   #null이 있는지 여부를 물을때

Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [36]:
obj.isnull().sum()  #True인 것만 합쳐서 출력함

1

## 데이터프레임

 - 데이터프레임은 2차원 배열, R의 데이터프레임에서 유래
 - 데이터프레임의 열은 각각 시리즈 개체
 - 시리즈를 열백터하고 하면 데이터프레임은 여러개의 열백터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 백터 또는 행렬
 - 선형대수학에서 열 벡터(mx1행렬)는 m 원소들의 단일 열 행렬
 - 행 벡터(1xm 행렬)은 m원소들의 단일 행 행렬
 - 리스트, 딕셔너리, 배열 등 다양한 데이터로부터 생성
 - 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있음.
 

In [43]:
# 배열 - > 데이터프레임

ar = np.random.randint(100,120,size=(3,3))
print(ar,type(ar),'\n')
df = pd.DataFrame(ar,index=['d1','d2','d3'], 
                  columns=['pd','sales','int'])
print(df,type(df))

[[105 112 118]
 [106 105 119]
 [108 115 112]] <class 'numpy.ndarray'> 

     pd  sales  int
d1  105    112  118
d2  106    105  119
d3  108    115  112 <class 'pandas.core.frame.DataFrame'>


pandas indexing
- iloc : integer location의 약어, 데이터프레임의 행이나 칼럼의 순서를 나타내는 정수로 특정값을 추출해오는 방법
- loc : 인덱스명, 칼럼명을 직접 적거나 특정 조건식을 써줌으로써 사람이 읽기 좋은 방법으로 데이터에 접근하는 방법

In [44]:
# 행선택
df.iloc[1,1]    #2행 2열을 추출(pandas)

105

In [48]:
print(df.iloc[1])  #2행의 열을 추출(숫자를 직접써서 추출이 가능)

pd       106
sales    105
int      119
Name: d2, dtype: int32


In [47]:
print(df.loc['d2'])  #인덱스 이름을 통해서도 열을 추출할 수 있다.

pd       106
sales    105
int      119
Name: d2, dtype: int32


In [49]:
#특정 행,열 선택
print(df.iloc[1,1],'\n')       #행 : 1 , 열 : 1 =>iloc의 방식으로 선택하는방법
print(df.loc['d2','sales'])    #행 index: 'd2',열 index:'sales  => loc

105 

105


In [51]:
# 행, 열 추가
df1 = df.copy()
df1.loc['d5'] = 0
df1

pd  sales  int
d1  105    112  118
d2  106    105  119
d3  108    115  112
d5    0      0    0

In [53]:
#[유의] =>열을 추가하는 방법   새로운 colemn을 추가(대괄호안에 새로운 이름을 넣는다.)
df1['pf'] = [100,100,100,0]  
df1

pd  sales  int   pf
d1  105  112.0  118  100
d2  106    NaN  119  100
d3  108  115.0  112  100
d5    0    0.0    0    0

In [55]:
print(type(df1.pf))    #데이터의 타입은 시리즈
df1.pf

<class 'pandas.core.series.Series'>


d1    100
d2    100
d3    100
d5      0
Name: pf, dtype: int64

In [52]:
#원소 값 변경
df1.iloc[1,1] = np.nan  #nan = null과 동일
df1

pd  sales  int
d1  105  112.0  118
d2  106    NaN  119
d3  108  115.0  112
d5    0    0.0    0

In [56]:
# 사전 -> 데이터프레임
sp1 = np.arange(1,6) 
df = pd.DataFrame({
    'col1':sp1,
    'col2':sp1 * 2,
    'col3':['A','B','C','D','E'],
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [96]:
#딕셔너리에서 값이 스칼라이면 인덱스 필요
dic = {'A':1,'B':2,'C':3,'D':4}
columns = ['a','b','c','d','e']
index = [1,2,3,4]

df_dic = pd.DataFrame(dic,index)
print(df_dic)

   A  B  C  D
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4
4  1  2  3  4


In [60]:
# 리스트 -> 데이터프레임
a = np.random.randint(1,5,size=(10,5))
list1 = a.tolist()
list1   #리스트형식
index = np.arange(1,11)
df = pd.DataFrame(list1,index,columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
1    3   4   2   1   1
2    3   1   2   1   4
3    3   3   2   2   1
4    2   2   2   1   3
5    4   3   4   3   4
6    4   4   3   3   2
7    2   1   1   1   1
8    1   2   3   3   4
9    3   1   3   3   2
10   4   3   2   2   3

In [66]:
# 데이터프레임을 -> 배열,리스트,딕셔너리
ar = df.values
print(ar,type(ar),'\n')
li = df.values.tolist()  #리스트로 바꾸기 위해서는 value뒤에 tolist를 붙인다
print(li,type(li),'\n')   
dict = df.to_dict('list')   #딕셔너리는 column별 리스트로 만들어야 하기 때문이다
print(dict,type(dict))

[[3 4 2 1 1]
 [3 1 2 1 4]
 [3 3 2 2 1]
 [2 2 2 1 3]
 [4 3 4 3 4]
 [4 4 3 3 2]
 [2 1 1 1 1]
 [1 2 3 3 4]
 [3 1 3 3 2]
 [4 3 2 2 3]] <class 'numpy.ndarray'> 

[[3, 4, 2, 1, 1], [3, 1, 2, 1, 4], [3, 3, 2, 2, 1], [2, 2, 2, 1, 3], [4, 3, 4, 3, 4], [4, 4, 3, 3, 2], [2, 1, 1, 1, 1], [1, 2, 3, 3, 4], [3, 1, 3, 3, 2], [4, 3, 2, 2, 3]] <class 'list'> 

{'c1': [3, 3, 3, 2, 4, 4, 2, 1, 3, 4], 'c2': [4, 1, 3, 2, 3, 4, 1, 2, 1, 3], 'c3': [2, 2, 2, 2, 4, 3, 1, 3, 3, 2], 'c4': [1, 1, 2, 1, 3, 3, 1, 3, 3, 2], 'c5': [1, 4, 1, 3, 4, 2, 1, 4, 2, 3]} <class 'dict'>


In [ ]:
# Q. 배열, 리스트, 딕셔너리로 데이터 프레임을 생성한 후 다시 배열, 리스트, 딕셔너리로 변환하여 출력하세요

In [87]:
ar = np.random.randint(1,10,size=(10,5))
print(ar,type(ar),'\n')
df = pd.DataFrame(ar,index=['d1','d2','d3','d4','d5','d6','d7','d8','d9','d10'], 
                  columns=['pd','sales','int','prt','iot'])
print(df,type(df))

[[5 8 1 4 2]
 [2 1 5 8 2]
 [4 3 2 8 5]
 [5 2 7 7 3]
 [3 6 1 6 7]
 [5 7 3 1 3]
 [6 9 9 3 3]
 [7 1 5 7 2]
 [9 6 6 2 3]
 [9 3 4 6 4]] <class 'numpy.ndarray'> 

     pd  sales  int  prt  iot
d1    5      8    1    4    2
d2    2      1    5    8    2
d3    4      3    2    8    5
d4    5      2    7    7    3
d5    3      6    1    6    7
d6    5      7    3    1    3
d7    6      9    9    3    3
d8    7      1    5    7    2
d9    9      6    6    2    3
d10   9      3    4    6    4 <class 'pandas.core.frame.DataFrame'>


c1  c2  c3  c4  c5
1    3   1   1   4   1
2    3   3   1   2   2
3    3   4   2   2   1
4    4   1   3   4   2
5    1   2   4   2   1
6    4   2   1   1   1
7    1   3   3   2   3
8    1   3   2   4   1
9    4   4   4   4   1
10   3   1   2   3   1

In [76]:
a = np.random.randint(1,10,size=(10,5))
list1 = a.tolist()
list1
index = np.arange(1,11)
df = pd.DataFrame(list1,index,columns=['k1','k2','k3','k4','k5'])
df

k1  k2  k3  k4  k5
1    1   4   4   9   7
2    5   7   6   9   7
3    7   6   8   7   9
4    5   3   7   1   3
5    2   6   1   8   5
6    2   2   9   7   9
7    2   5   8   4   3
8    7   2   1   9   4
9    7   5   6   7   2
10   3   8   5   7   9

In [79]:
ar = df.values
print(ar,type(ar),'\n')
li = df.values.tolist()
print(li,type(li),'\n')
dict = df.to_dict('list')
print(dict,type(dict))


[[1 4 4 9 7]
 [5 7 6 9 7]
 [7 6 8 7 9]
 [5 3 7 1 3]
 [2 6 1 8 5]
 [2 2 9 7 9]
 [2 5 8 4 3]
 [7 2 1 9 4]
 [7 5 6 7 2]
 [3 8 5 7 9]] <class 'numpy.ndarray'> 

[[1, 4, 4, 9, 7], [5, 7, 6, 9, 7], [7, 6, 8, 7, 9], [5, 3, 7, 1, 3], [2, 6, 1, 8, 5], [2, 2, 9, 7, 9], [2, 5, 8, 4, 3], [7, 2, 1, 9, 4], [7, 5, 6, 7, 2], [3, 8, 5, 7, 9]] <class 'list'> 

{'k1': [1, 5, 7, 5, 2, 2, 2, 7, 7, 3], 'k2': [4, 7, 6, 3, 6, 2, 5, 2, 5, 8], 'k3': [4, 6, 8, 7, 1, 9, 8, 1, 6, 5], 'k4': [9, 9, 7, 1, 8, 7, 4, 9, 7, 7], 'k5': [7, 7, 9, 3, 5, 9, 3, 4, 2, 9]} <class 'dict'>


In [88]:
# 리스트
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.Series(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'])
print(df1,'\n')
print(df1.tolist(),type(df1.tolist()),'\n')

# 딕셔너리
df2 = pd.DataFrame({
    '커피':4000,
    '쿠키':3000,
    '케이크':6500
},index=['가격'])
print(df2,'\n')
print(df2.to_dict('list'),type(df2.to_dict('list')),'\n')

# 배열
df3 = pd.DataFrame(np.random.randint(1,10,size=(3,3)),index=['1반','2반','3반'],
                   columns=['달리기','줄다리기','무궁화'])
print(df3,'\n')
print(df3.values)
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['차림표'])
print(df1,'\n')
print(df1.values.tolist(),type(df1.values.tolist()),'\n')


메뉴1      냉면
메뉴2     칼국수
메뉴3    잔치국수
메뉴4     수제비
메뉴5      우동
dtype: object 

['냉면', '칼국수', '잔치국수', '수제비', '우동'] <class 'list'> 

      커피    쿠키   케이크
가격  4000  3000  6500 

{'커피': [4000], '쿠키': [3000], '케이크': [6500]} <class 'dict'> 

    달리기  줄다리기  무궁화
1반    9     4    7
2반    6     4    2
3반    5     3    4 

[[9 4 7]
 [6 4 2]
 [5 3 4]]
      차림표
메뉴1    냉면
메뉴2   칼국수
메뉴3  잔치국수
메뉴4   수제비
메뉴5    우동 

[['냉면'], ['칼국수'], ['잔치국수'], ['수제비'], ['우동']] <class 'list'> 



In [94]:
# file 생성, 저장[to csv("저장위치")], 읽기(read_csv)
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.Series(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'])
df1.to_csv("./dataset/file_data.csv", index=None)   
#파일을 저장할 때는 df1.to_csv를 사용하고("")안에 저장할 위치를 넣고, index=None를 넣어야 한다.
file_data = pd.read_csv("./dataset/file_data.csv")   #저장한 파일을 읽는 방법은 pd.read_csv를 사용하면 된다.
file_data       

0
0    냉면
1   칼국수
2  잔치국수
3   수제비
4    우동

In [99]:
li = ['안성탕면','사리곰탕','짜파게티','우동','신라면','무파마']
dfs1 = pd.Series(li, index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5','메뉴6'])
dfs1.to_csv("./dataset/file_data.csv",index=None)
file_data = pd.read_csv("./dataset/file_data.csv")
file_data

0
0  안성탕면
1  사리곰탕
2  짜파게티
3    우동
4   신라면
5   무파마